### ISSUE TITLE
Need new payment options for different kinds of subscribers

### ISSUE THREAD

**Issue by davidrleonard** [civicquarterly/cq-pay#8]
Need 3 tiers of payment options:

* **Recurring**: Recurring $9/quarter billing for auto-renew print subscribers
* **One-time**: One-time $9 billing for subscribers who just want one issue
* **Donor**: A one-time $9 bill (or perhaps however much they want to give?), no issue will be shipped to them

**Comment by jeremiak** [comment]
With #10 we'll cover recurring and donor. I think so far that's good enough so I'm going to close this issue out when that PR is merged.
